name: CI

on:
  push:
    branches:
      - main
      - case-key-paths
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    name: macOS 15
    runs-on: macOS-15
    strategy:
      matrix:
        config:
          - debug
          - release
    steps:
      - name: Checkout Package
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: View Swift Version
        run: swift --version

      - name: Build Package
        run: swift build -c ${{ matrix.config }}

      - name: Run Tests
        run: swift test -c ${{ matrix.config }}
