name: Docc

on:
  release:
    types:
      - published
  push:
    branches:
      - main

concurrency:
  group: docc-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout Package
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2.3.0
        with:
          swift-version: "6.0.0"

      - name: Checkout gh-pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: docs-out
        continue-on-error: true

      - name: Create gh-pages directory if not exists
        run: |
          if [ ! -d "docs-out" ]; then
            mkdir -p docs-out
            cd docs-out
            git init
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git commit --allow-empty -m "Initial commit"
          fi

      - name: Build documentation
        run: |
          rm -rf docs-out/.git
          rm -rf docs-out/main
          rm -rf docs-out/latest

          # Get all tags, if less than 94 tags exist, use all available tags
          tag_count=$(git tag | wc -l)
          if [ $tag_count -lt 94 ]; then
            tags=$(git tag)
          else
            tags=$(git tag | tail -n +94)
          fi

          # Add main and latest to the list
          all_releases="main latest $tags"

          for tag in $all_releases; do
            echo "⏳ Generating documentation for $tag release."

            if [ -d "docs-out/$tag" ]; then
              echo "✅ Documentation for $tag already exists."
            else
              if [ "$tag" == "latest" ]; then
                latest_tag=$(git tag | tail -n 1)
                if [ -n "$latest_tag" ]; then
                  git checkout -f "$latest_tag"
                else
                  echo "⚠️ No tags found, skipping latest"
                  continue
                fi
              else
                git checkout -f "$tag"
              fi

              # Check if Swift supports generate-documentation
              if swift package --help | grep -q "generate-documentation"; then
                swift package \
                  --allow-writing-to-directory docs-out/"$tag" \
                  generate-documentation \
                  --target Rex \
                  --output-path docs-out/"$tag" \
                  --transform-for-static-hosting \
                  --hosting-base-path /swift-rex/"$tag" \
                  && echo "✅ Documentation generated for $tag release." \
                  || echo "⚠️ Documentation failed for $tag."
              else
                echo "⚠️ Swift version does not support generate-documentation, skipping $tag"
                echo "Current Swift version:"
                swift --version
              fi
            fi
          done

      - name: Fix permissions
        run: "sudo chown -R $USER docs-out"

      - name: Publish documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs-out
          single-commit: true
